# Generated by Django 6.0.2 on 2026-02-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('REGISTER', 'REGISTER'), ('LOGIN', 'LOGIN'), ('LOGOUT', 'LOGOUT'), ('TOKEN_REFRESH', 'TOKEN_REFRESH'), ('PASSWORD_CHANGE', 'PASSWORD_CHANGE'), ('PROFILE_UPDATE', 'PROFILE_UPDATE'), ('PASSWORD_RESET_REQUEST', 'PASSWORD_RESET_REQUEST'), ('PASSWORD_RESET_CONFIRM', 'PASSWORD_RESET_CONFIRM'), ('USERS_LIST', 'USERS_LIST'), ('ACCOUNT_DELETE', 'ACCOUNT_DELETE')], max_length=30),
        ),
    ]
