# Generated by Django 6.0.2 on 2026-02-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('USER', 'USER'), ('ANALYST', 'ANALYST')], default='USER', max_length=20),
        ),
    ]
