# Generated by Django 6.0.2 on 2026-02-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_email_verified',
            new_name='email_verified',
        ),
    ]
