# Generated by Django 6.0.2 on 2026-02-10 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('vulns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='vulnerability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vulns.vulnerability'),
        ),
    ]
