# Generated by Django 6.0.2 on 2026-02-10 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.PositiveIntegerField()),
                ('protocol', models.CharField(default='tcp', max_length=10)),
                ('state', models.CharField(default='open', max_length=20)),
                ('service', models.CharField(blank=True, max_length=100)),
                ('version', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='assets.asset')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('asset', 'port', 'protocol')},
            },
        ),
    ]
